name: WTTV4 - Wondrously Teslafied Trans-dimensional Vortex 4
favicon: null
layout_spectrum: 0.9504429555963725
typography_spectrum: 0.4548814801964909
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7435611577238888
  lightness: 0.5262073439080268
  saturation: 0.5786880117375404
  rhythmicContrast: 0.6426902734674513
purpose: []
